### ISSUE TITLE
Tracking your Todo features

### ISSUE THREAD

**Issue by GeorgeS2019** [gudatr/Godot4CharacterCreator#2]
- [ ] Morphs the characters mood expression dynamically
- [ ] Makes them blink in realistic intervals
- [ ] Lip syncs based on AudioBus throughput
- [ ] Adds random variations to eye and head movement
- [ ] Adds the ability for the characters to head track a position or node

This is Godot Digital Human using MakeHuman framework.

Many if not all of your suggested ToDo could be re-used for other Godot Humanoid framework for avatars coming from projects alternative to MakeHuman

**Comment by gudatr** [comment]
A good idea that I will make sure to keep in mind
